# Generated by Django 2.0.3 on 2018-03-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetSta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netsta_code', models.TextField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stationday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='stationday of data')),
                ('ofa_mod_ts', models.DateTimeField(verbose_name='timestamp of modified time of OFA file')),
                ('ofc_mod_ts', models.DateTimeField(verbose_name='timestamp of modified time of OFC file')),
                ('net_sta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falcon.NetSta')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_value', models.FloatField()),
                ('high_value', models.IntegerField()),
                ('low_value', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='falcon.Channel')),
                ('stationday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falcon.Stationday')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='stationday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='falcon.Stationday'),
        ),
        migrations.AlterUniqueTogether(
            name='stationday',
            unique_together={('net_sta', 'date')},
        ),
    ]
