# Generated by Django 2.0.3 on 2018-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stationday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'managed': True},
        ),
    ]
