# Generated by Django 2.0.3 on 2018-03-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0002_auto_20180316_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netsta',
            options={'managed': True},
        ),
    ]
