# Generated by Django 2.0.3 on 2018-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falcon', '0004_auto_20180328_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesAhl',
            fields=[
                ('value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avg_value', models.FloatField()),
                ('high_value', models.IntegerField()),
                ('low_value', models.IntegerField()),
            ],
            options={
                'db_table': 'values_ahl',
                'managed': False,
            },
        ),
    ]
